### ISSUE TITLE
Intermittent TypeError on piped archive.finalize

### ISSUE THREAD

**Issue by disbelief** [ctalkington/node-archiver#120]
I'm seeing the following error happen occasionally and can't always recreate it with the same input.

```
TypeError: Argument must be a string
    at Buffer.write (buffer.js:353:25)
    at ZipArchiveOutputStream._writeCentralFileHeader (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:265:14)
    at null.<anonymous> (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:118:10)
    at Array.forEach (native)
    at ZipArchiveOutputStream._finish (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:117:17)
    at ArchiveOutputStream.finish (/app/node_modules/archiver/node_modules/zip-stream/node_modules/compress-commons/lib/archivers/archive-output-stream.js:105:8)
    at ZipStream.finalize (/app/node_modules/archiver/node_modules/zip-stream/lib/zip-stream.js:109:8)
    at Zip.finalize (/app/node_modules/archiver/lib/plugins/zip.js:34:15)
    at Archiver._moduleFinalize (/app/node_modules/archiver/lib/core.js:124:18)
    at Archiver._finalize (/app/node_modules/archiver/lib/core.js:89:8)
```

The above error is thrown when calling archive.finalize. This is happening within the context of an express application. Here's essentially what I'm doing:

```javascript
router.get('/:id', function (req, res, next) {
  var archive = archiver('zip');
   archive.on('error', function (err) {
     console.error("archive error handler", err);
     // res.status(500).send({error: err.message});
     next(err);
   });
   res.on('close', function () {
     console.log('Archive wrote %d bytes', archive.pointer());
     return res.status(200).send('OK').end();
   });
   res.attachment('archive.zip');
   var inputStream = getInputStreamFor(req.params.id);
   archive.append(inputStream, { name: 'archive.zip' });
   archive.pipe(res);
   archive.finalize();
});

```
(note this is an over-simplification of the code without business logic and callbacks, etc. but the code does work most of the time)

Might not be a bug with node-archiver but if not, perhaps you might know what the cause could be?

**Comment by ctalkington** [comment]
are these bigger archives? file count wise?

don't think its related but you generally want to pipe before append.

**Comment by disbelief** [comment]
Not huge file count wise: I've been investigating one with about 20 files in it. They were rather large files though: ~500MB each.

Could it be a memory issue?

> don't think its related but you generally want to pipe before append.

Right sorry I had this backwards in my example above. It's actually like this in my application:

```javascript
var archive = archiver('zip');
// ...
res.attachment('archive.zip');
archive.pipe(res);
var inputStream = getInputStreamFor(req.params.id);
archive.append(inputStream, { name: 'archive.zip' });
archive.finalize();
```

**Comment by ctalkington** [comment]
i think its hitting ZIP64 which hasn't been thoroughly tested. based on the line its failing at.

**Comment by ctalkington** [comment]
moved to ctalkington/node-compress-commons#12
